spring.application.name=salon-management-server
spring.config.import=optional:file:.env[.properties]
server.port=${PORT}


salonhq.env=${ENV}
salonhq.mongo.db.name=${DB_NAME}
salonhq.mongo.db.user=${DB_USER}
salonhq.mongo.db.cluster=${DB_CLUSTER}
salonhq.mongo.db.password=${DB_PASSWORD}
salonhq.mongo.db.appName=${DB_APP_NAME}
salonhq.mongo.local.url=${LOCAL_DB_URL}

salonhq.jwt.secret=${JWT_SECRET}
salonhq.jwt.expiration=${JWT_EXPIRATION}

# Actuator
# Expose selected endpoints over HTTP
management.endpoints.web.exposure.include=health,info,metrics,env,loggers
management.endpoints.web.base-path=/actuator
# Health endpoint details: always | when_authorized | never
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
# Info endpoint - populate /actuator/info
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
info.app.name=${spring.application.name}
info.app.version=@project.version@

