spring.application.name=salon-management-server
spring.config.import=optional:file:.env[.properties]
server.port=${PORT}


salonhq.env=${ENV}
salonhq.mongo.db.name=${DB_NAME}
salonhq.mongo.db.user=${DB_USER}
salonhq.mongo.db.cluster=${DB_CLUSTER}
salonhq.mongo.db.password=${DB_PASSWORD}
salonhq.mongo.db.appName=${DB_APP_NAME}
salonhq.mongo.local.url=${LOCAL_DB_URL}

salonhq.jwt.secret=${JWT_SECRET}
salonhq.jwt.expiration=${JWT_EXPIRATION}

